project:
  type: website

website:
  title: "ğŸ¶Folk Flow"
  navbar:
    left:
      - text: Introduction
        href: "Project Proposal_Group 13.html"
      - text: Discovery
        menu: 
        - text: Data Wrangling
          href: data_wrangling.qmd
      - text: Shiny App
        menu: 
        - text: User Guide 
          href: user_guide.pdf
        - text: ShinyApp
          href: https://vaa-project-group13.shinyapps.io/Project_Shiny/
      - text: Project Poster 
        href: "coming Soon"
      - text: Team
        href: team_intro.qmd
      - text: ğŸ“ Meeting Minutes
        menu: 
          - text: Meeting Minute 1 
            href: "Meeting_Minutes/Meeting_Minutes_1.html"
          - text: Meeting Minute 2 
            href: "Meeting_Minutes/Meeting_Minutes_2.html"
          - text: Meeting Minute 3 
            href: "Meeting_Minutes/Meeting_Minutes_3.html"        


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

